### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by ahpnils** [DvdChe/social-pipe#1]
When trying to run social-pipe with Python 3.7.4, I got the following error message : 
```Traceback (most recent call last):
  File "social-pipe.py", line 16, in <module>
    import tweepy
  File "/XXX/social-pipe/lib/python3.7/site-packages/tweepy/__init__.py", line 17, in <module>
    from tweepy.streaming import Stream, StreamListener
  File "/XXX/social-pipe/lib/python3.7/site-packages/tweepy/streaming.py", line 358
    def _start(self, async):
                         ^
SyntaxError: invalid syntax
```

This was tested with the following platform : 
- OS : macOS Mojave 10.14.5 (18F132)
- Python 3.7.4 from pkgsrc
- py37-virtualenv-16.6.1 (from pkgsrc)
- py37-setuptools-41.0.1 (from pkgsrc)
- requirements installed from requirements.txt

**Comment by DvdChe** [comment]
Hey,

I succeed to reproduce your issue and it seems issue seems to be related to an incompatibility with tweepy and python 3.7
I think i found a solution here : https://github.com/tweepy/tweepy/issues/1063 and it appear to works for me.

Cheers
