### ISSUE TITLE
Missing LogLevel directive in configuration

### ISSUE THREAD

**Issue by ahpnils** [DvdChe/social-pipe#2]
When trying to run social-pipe, I got the following error message : 
```
Traceback (most recent call last):
  File "social-pipe.py", line 61, in <module>
    LogLevel = int(conf['OPTIONS']['LogLevel'])
  File "/opt/pkg/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'LogLevel'
```

It turns out the `LogLevel` directive is missing from the `social-pipe.conf` file. I also noticed it is also missing in the `social-pipe.conf.tpl` file.

This was tested with the following platform :

- OS : macOS Mojave 10.14.5 (18F132)
- Python 3.6.9 from pkgsrc
- py36-virtualenv-16.6.1 (from pkgsrc)
- py36-setuptools-41.0.1 (from pkgsrc)
- requirements installed from requirements.txt

**Comment by DvdChe** [comment]
Hey,

this is fixed in the following commit : 
https://github.com/DvdChe/social-pipe/commit/7a156e2a31a5cf8d9fbcf149334ee0ce923432c5
